"""Корзина и избранное для пользователей

Revision ID: cdf9e91d2804
Revises: 39488889b390
Create Date: 2025-03-13 12:07:17.178690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf9e91d2804'
down_revision: Union[str, None] = '39488889b390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cartitems_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cartitems_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cartitems'))
    )
    op.create_index(op.f('ix_cartitems_id'), 'cartitems', ['id'], unique=False)
    op.create_table('user_favorite_products',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_user_favorite_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorite_products_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_favorite_products'))
    )
    op.create_index(op.f('ix_user_favorite_products_id'), 'user_favorite_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_products_id'), table_name='user_favorite_products')
    op.drop_table('user_favorite_products')
    op.drop_index(op.f('ix_cartitems_id'), table_name='cartitems')
    op.drop_table('cartitems')
    # ### end Alembic commands ###
